channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.10.2
  - cloudpickle==3.1.1
  - numpy==1.24.3
  - packaging==23.2
  - psutil==7.0.0
  - pyyaml==6.0.2
  - scikit-learn==1.2.2
  - scipy==1.10.1
name: mlflow-env
